name: q_learn
description: "A new Flutter project."

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  dio: ^5.5.0+1
  get_it: ^7.7.0
  json_annotation: ^4.9.0
  auto_route: ^8.2.0
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  awesome_dio_interceptor: ^1.2.0
  oktoast: ^3.4.0
  flutter_form_builder: ^9.3.0
  form_builder_validators: ^10.0.1
  flutter_rating_bar: ^4.0.1
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  json_serializable: ^6.7.1
  build_runner: ^2.4.8
  retrofit_generator: ^8.1.1 # required dart >=2.19
  auto_route_generator: ^8.0.0
  riverpod_generator: ^2.4.0
  custom_lint: ^0.6.4
  riverpod_lint: ^2.3.10

flutter:
  uses-material-design: true
